export function mean(values=[]){if(!values.length)return 0;return values.reduce((sum,value)=>sum+value,0)/values.length}
export function standardDeviation(values=[]){if(values.length<2)return 0;const avg=mean(values);const variance=values.reduce((sum,value)=>sum+((value-avg)**2),0)/(values.length-1);return Math.sqrt(variance)}
export function coefficientOfVariation(values=[]){const avg=mean(values);if(!avg)return 0;return(standardDeviation(values)/Math.abs(avg))*100}
export function dualTaskCost(singleValue,dualValue,higherIsBetter=true){if(singleValue===0||!Number.isFinite(singleValue)||!Number.isFinite(dualValue))return null;return higherIsBetter?((singleValue-dualValue)/Math.abs(singleValue))*100:((dualValue-singleValue)/Math.abs(singleValue))*100}
export function rawDifference(singleValue,dualValue){return dualValue-singleValue}
export function zDeviation(referenceValues,observedValue,higherIsBetter=true){const sd=standardDeviation(referenceValues);if(!sd)return 0;const z=(observedValue-mean(referenceValues))/sd;return higherIsBetter?-z:z}
export function accuracy(responses=[]){if(!responses.length)return 0;return(responses.filter(r=>r.correct).length/responses.length)*100}
export function median(values=[]){if(!values.length)return 0;const sorted=[...values].sort((a,b)=>a-b);const middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:(sorted[middle-1]+sorted[middle])/2}
export function classifyProfile(motorDtc,cognitiveDtc,threshold=8){const motorHigh=motorDtc>=threshold;const cognitiveHigh=cognitiveDtc>=threshold;if(motorHigh&&cognitiveHigh)return'Mutual interference';if(motorHigh)return'Motor-sensitive';if(cognitiveHigh)return'Cognitive-sensitive';if(motorDtc<-threshold&&cognitiveDtc>=threshold)return'Motor-prioritisation shift';if(cognitiveDtc<-threshold&&motorDtc>=threshold)return'Cognitive-prioritisation shift';return'Low observed interference'}
export function combinedInterference(motorDtc,cognitiveDtc){const positiveMotor=Math.max(0,motorDtc);const positiveCognitive=Math.max(0,cognitiveDtc);return Math.sqrt((positiveMotor**2+positiveCognitive**2)/2)}
export function summariseSession(session){const motorSingle=session.motorBaseline?.meanCadence??0;const motorDual=session.dualTask?.meanCadence??0;const cognitiveSingle=session.cognitiveBaseline?.accuracy??0;const cognitiveDual=session.dualTask?.accuracy??0;const motorDtc=dualTaskCost(motorSingle,motorDual,true)??0;const cognitiveDtc=dualTaskCost(cognitiveSingle,cognitiveDual,true)??0;return{motorDtc,cognitiveDtc,combined:combinedInterference(motorDtc,cognitiveDtc),profile:classifyProfile(motorDtc,cognitiveDtc),motorRawDifference:rawDifference(motorSingle,motorDual),cognitiveRawDifference:rawDifference(cognitiveSingle,cognitiveDual)}}
export function estimateFrontier(points=[],threshold=12){const sorted=[...points].sort((a,b)=>(a.motorLoad+a.cognitiveLoad)-(b.motorLoad+b.cognitiveLoad));const first=sorted.find(point=>point.combinedInterference>=threshold);if(!first)return{status:'not reached',point:null};return{status:'observed',point:first}}
