import{assessmentProtocols,cognitiveParadigms,getProtocol}from'./protocols.js';
import{MotorSimulator,generateCapacityPoints,historicalSessions}from'./simulator.js';
import{CMISession}from'./session.js';
import{createStimulus}from'./tasks.js';
import{summariseSession,estimateFrontier,combinedInterference}from'./analytics.js';
import{exportJson,exportCsv}from'./export.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={session:null,summary:null,phase:0,phaseTimer:null,sampleTimer:null,stimulusTimer:null,currentStimulus:null,stimulusShownAt:0,stimulusIndex:0,seconds:0,simulator:new MotorSimulator(65),capacity:generateCapacityPoints(),history:historicalSessions()};
const metric=(label,value,unit='',note='')=>`<article class="metric-card"><div class="metric-label">${label}</div><div class="metric-value">${value}${unit?`<small>${unit}</small>`:''}</div>${note?`<div class="metric-note">${note}</div>`:''}</article>`;
const defaultResult=()=>({motorDtc:10.8,cognitiveDtc:11.6,combined:combinedInterference(10.8,11.6),profile:'Mutual interference'});
const result=()=>state.summary?summariseSession(state.summary):defaultResult();

function bars(el,rows){el.innerHTML=rows.map(r=>`<div class="bar-row"><div class="bar-label">${r.label}</div><div class="bar-track"><div class="bar-fill ${r.p>=20?'danger':r.p>=10?'warn':''}" style="width:${Math.max(0,Math.min(100,r.p))}%"></div></div><div class="bar-value">${r.value}</div></div>`).join('')}
function overview(){const r=result();$('#overviewMetrics').innerHTML=[metric('Motor dual-task cost',r.motorDtc.toFixed(1),'%','Positive = deterioration'),metric('Cognitive dual-task cost',r.cognitiveDtc.toFixed(1),'%','Accuracy-based'),metric('Combined interference',r.combined.toFixed(1),'','Descriptive vector magnitude'),metric('Clock uncertainty','±4','ms','Prototype timing estimate')].join('');$('#profileBadge').textContent=r.profile;bars($('#overviewInterference'),[{label:'Motor cost',p:r.motorDtc*3,value:`${r.motorDtc.toFixed(1)}%`},{label:'Cognitive cost',p:r.cognitiveDtc*3,value:`${r.cognitiveDtc.toFixed(1)}%`},{label:'Combined',p:r.combined*3,value:r.combined.toFixed(1)}]);const q=[['Protocol version',state.summary?.protocolVersion??'1.0.0'],['Priority instruction',state.summary?.priority??'Equal priority'],['Clock source','performance.now()'],['Event reconstruction','Complete'],['Data mode','Synthetic / local']];$('#qualityList').innerHTML=q.map(x=>`<div class="quality-item"><span class="quality-label">${x[0]}</span><span class="quality-value">${x[1]}</span></div>`).join('')}
function rail(protocol,index=-1){$('#phaseRail').innerHTML=protocol.phases.map((p,i)=>`<div class="phase-row ${i===index?'active':''} ${i<index?'done':''}"><div class="phase-index">${i<index?'✓':i+1}</div><div><strong>${p.label}</strong><small>${p.detail}</small></div></div>`).join('')}
function provenance(){const p=state.session?getProtocol(state.session.protocolId):getProtocol($('#protocolSelect')?.value);const x=[['Protocol',p.version],['Task',p.paradigm],['Priority',state.session?.priority??$('#prioritySelect')?.value??'equal'],['Device','simulator-cycle-001'],['Adapter','1.0.0'],['Clock','monotonic']];$('#provenanceList').innerHTML=x.map(v=>`<dt>${v[0]}</dt><dd>${v[1]}</dd>`).join('')}
function nav(view){$$('.view').forEach(n=>n.classList.toggle('active',n.id===`view-${view}`));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$('#pageTitle').textContent=$(`.nav-item[data-view="${view}"]`)?.textContent.replace(/^\d+/,'').trim()??'Overview';if(view==='overview')overview();if(view==='capacity')capacityMap();if(view==='longitudinal')longitudinal();if(view==='data')eventPreview();window.scrollTo({top:0,behavior:'smooth'})}
function screen(id){$$('.assessment-screen').forEach(n=>n.classList.toggle('active-screen',n.id===id))}
function start(){const protocol=getProtocol($('#protocolSelect').value),participantId=$('#participantId').value.trim()||'VP-CMI-001',priority=$('#prioritySelect').value,motorTarget=Number($('#motorTargetSelect').value);state.simulator=new MotorSimulator(motorTarget);state.session=new CMISession({participantId,protocol,priority,motorTarget});state.summary=null;state.phase=0;state.stimulusIndex=0;$('#assessmentState').textContent='Running';$('#assessmentState').className='badge positive';screen('assessmentRun');provenance();runPhase()}
function phaseInfo(){const protocol=getProtocol(state.session.protocolId);return{protocol,phase:protocol.phases[state.phase]}}
function clearTimers(){clearInterval(state.phaseTimer);clearInterval(state.sampleTimer);clearTimeout(state.stimulusTimer);state.phaseTimer=state.sampleTimer=state.stimulusTimer=null;state.currentStimulus=null}
function runPhase(){clearTimers();const{protocol,phase}=phaseInfo();state.session.addTransition(phase.id,'started');rail(protocol,state.phase);$('#phaseEyebrow').textContent=`Phase ${state.phase+1} of ${protocol.phases.length}`;$('#phaseTitle').textContent=phase.label;const ins={motor:'Maintain the target cadence as steadily as possible.',cognitive:'Complete the cognitive task accurately and promptly. Motor input is paused.',dual:state.session.priority==='equal'?'Maintain both tasks with equal priority.':state.session.priority==='motor'?'Prioritise cadence while still responding to the cognitive task.':'Prioritise cognitive accuracy while continuing the motor task.'};$('#phaseInstruction').textContent=ins[phase.id];state.seconds=protocol.phaseDurationSec;timerText();const motor=phase.id!=='cognitive',cog=phase.id!=='motor';$('.motor-card').style.opacity=motor?'1':'.35';$('.cognitive-card').style.opacity=cog?'1':'.35';$('#cognitiveStimulus').textContent=cog?'READY':'PAUSED';$('#cadenceTarget').textContent=`${state.session.motorTarget} rpm`;$('#cadenceSlider').value=state.session.motorTarget;state.phaseTimer=setInterval(()=>{state.seconds--;timerText();if(state.seconds<=0)completePhase()},1000);if(motor)state.sampleTimer=setInterval(()=>sampleMotor(phase.id,protocol.difficulty),250);if(cog)scheduleStimulus(protocol.paradigm,phase.id,protocol.difficulty)}
function timerText(){$('#phaseTimer').textContent=`00:${String(Math.max(0,state.seconds)).padStart(2,'0')}`}
function sampleMotor(phase,difficulty){const cadence=state.simulator.sample({dualTask:phase==='dual',cognitiveLoad:difficulty});state.session.addMotorSample(phase,cadence);$('#cadenceValue').textContent=Math.round(cadence);const b=document.createElement('div');b.className='spark-bar';b.style.height=`${Math.max(8,Math.min(100,cadence))/100*34}px`;$('#cadenceSpark').appendChild(b);while($('#cadenceSpark').children.length>42)$('#cadenceSpark').firstChild.remove();$('#eventCount').textContent=state.session.events.length}
function scheduleStimulus(paradigm,phase,difficulty){const delay=Math.max(900,1800-difficulty*180)+Math.random()*550;state.stimulusTimer=setTimeout(()=>{if(!state.session||phaseInfo().phase.id!==phase)return;state.currentStimulus=createStimulus(paradigm,state.stimulusIndex++);state.stimulusShownAt=performance.now();state.session.addStimulus(phase,state.currentStimulus);$('#cognitiveStimulus').textContent=state.currentStimulus.label;$('#cognitiveStimulus').className='cognitive-stimulus';$('#eventCount').textContent=state.session.events.length;if(state.currentStimulus.expected==='hold')setTimeout(()=>{if(state.currentStimulus?.expected==='hold')respond('hold')},620);scheduleStimulus(paradigm,phase,difficulty)},delay)}
function respond(response){if(!state.currentStimulus||!state.session||phaseInfo().phase.id==='motor')return;const latency=performance.now()-state.stimulusShownAt;const e=state.session.addResponse(phaseInfo().phase.id,state.currentStimulus,response,latency);$('#accuracyValue').textContent=e.correct?'correct':'error';$('#rtValue').textContent=`${Math.round(latency)} ms`;$('#eventCount').textContent=state.session.events.length;state.currentStimulus=null;$('#cognitiveStimulus').textContent='·';$('#cognitiveStimulus').className='cognitive-stimulus idle'}
function completePhase(){if(!state.session)return;const{protocol,phase}=phaseInfo();state.session.addTransition(phase.id,'completed');state.phase++;state.phase>=protocol.phases.length?finish():runPhase()}
function finish(){clearTimers();state.summary=state.session.summary();const r=summariseSession(state.summary);screen('assessmentResults');$('#assessmentState').textContent='Complete';$('#resultProfile').textContent=r.profile;const sentences={'Mutual interference':'Both motor and cognitive performance degraded under combined load.','Motor-sensitive':'Motor performance showed greater degradation while cognition was relatively preserved.','Cognitive-sensitive':'Cognitive performance showed greater degradation while motor output was relatively preserved.','Low observed interference':'Both domains remained relatively stable under the tested combined load.'};$('#resultSummary').textContent=sentences[r.profile]??'Observed task-priority trade-off recorded.';$('#resultMetrics').innerHTML=[metric('Motor DTC',r.motorDtc.toFixed(1),'%','Single vs dual'),metric('Cognitive DTC',r.cognitiveDtc.toFixed(1),'%','Accuracy-based'),metric('Motor variability',state.summary.dualTask.cadenceCV.toFixed(1),'% CV','Dual-task cadence'),metric('Events',state.summary.eventCount,'','Reconstructable')].join('');bars($('#motorResultBars'),[{label:'Single task',p:100,value:`${state.summary.motorBaseline.meanCadence.toFixed(1)} rpm`},{label:'Dual task',p:state.summary.dualTask.meanCadence/Math.max(1,state.summary.motorBaseline.meanCadence)*100,value:`${state.summary.dualTask.meanCadence.toFixed(1)} rpm`}]);bars($('#cognitiveResultBars'),[{label:'Single task',p:state.summary.cognitiveBaseline.accuracy,value:`${state.summary.cognitiveBaseline.accuracy.toFixed(0)}%`},{label:'Dual task',p:state.summary.dualTask.accuracy,value:`${state.summary.dualTask.accuracy.toFixed(0)}%`}]);const today=new Date().toISOString().slice(0,10);state.history=[...state.history.filter(x=>x.date!==today),{date:today,motorDtc:r.motorDtc,cognitiveDtc:r.cognitiveDtc,reliability:.89}];overview();eventPreview();toast('Assessment complete — event stream preserved')}
function capacityMap(){const c=$('#capacityCanvas'),ctx=c.getContext('2d'),{width,height}=c,m={left:88,right:42,top:34,bottom:72},w=width-m.left-m.right,h=height-m.top-m.bottom,cw=w/5,ch=h/5;ctx.clearRect(0,0,width,height);ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);state.capacity.forEach(p=>{const x=m.left+(p.motorLoad-1)*cw,y=m.top+(5-p.cognitiveLoad)*ch,l=p.combinedInterference;ctx.fillStyle=l<9?'#d9e8e0':l<17?'#eee2cf':'#ead9d7';ctx.fillRect(x+2,y+2,cw-4,ch-4);ctx.fillStyle='#1d2525';ctx.font='600 17px sans-serif';ctx.textAlign='center';ctx.fillText(l.toFixed(1),x+cw/2,y+ch/2+4);ctx.fillStyle='#67706f';ctx.font='10px sans-serif';ctx.fillText(`M ${p.motorDtc.toFixed(0)} · C ${p.cognitiveDtc.toFixed(0)}`,x+cw/2,y+ch/2+22)});ctx.fillStyle='#67706f';ctx.font='11px sans-serif';for(let i=1;i<=5;i++){ctx.textAlign='center';ctx.fillText(String(i),m.left+(i-.5)*cw,height-46);ctx.textAlign='right';ctx.fillText(String(i),m.left-18,m.top+(5-i+.5)*ch+4)}ctx.fillStyle='#1d2525';ctx.font='600 12px sans-serif';ctx.textAlign='center';ctx.fillText('Motor demand →',m.left+w/2,height-18);ctx.save();ctx.translate(24,m.top+h/2);ctx.rotate(-Math.PI/2);ctx.fillText('Cognitive demand →',0,0);ctx.restore();const f=estimateFrontier(state.capacity,12),p=f.point??{motorLoad:5,cognitiveLoad:5,combinedInterference:0},r=result();$('#frontierStats').innerHTML=[[`M${p.motorLoad} × C${p.cognitiveLoad}`,'First observed ≥12 interference'],[p.combinedInterference.toFixed(1),'Combined interference at frontier'],[r.profile,'Current observed pattern'],['25 cells','Synthetic demonstration matrix']].map(x=>`<div class="frontier-stat"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}
function longitudinal(){const key=$('#longitudinalMetric')?.value??'combined',data=state.history.map(r=>({...r,value:key==='motor'?r.motorDtc:key==='cognitive'?r.cognitiveDtc:combinedInterference(r.motorDtc,r.cognitiveDtc)})),first=data[0],last=data.at(-1),change=(last.value-first.value)/first.value*100,w=980,h=320,p=48,vals=data.map(d=>d.value),min=Math.min(...vals)*.85,max=Math.max(...vals)*1.12,x=i=>p+i*((w-p*2)/Math.max(1,data.length-1)),y=v=>h-p-((v-min)/Math.max(.001,max-min))*(h-p*2),pts=data.map((d,i)=>`${x(i)},${y(d.value)}`).join(' ');$('#longitudinalChart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polyline fill="none" stroke="#315f5c" stroke-width="4" points="${pts}" vector-effect="non-scaling-stroke"/>${data.map((d,i)=>`<circle cx="${x(i)}" cy="${y(d.value)}" r="6" fill="#315f5c"/><text x="${x(i)}" y="${y(d.value)-14}" text-anchor="middle" font-size="11">${d.value.toFixed(1)}</text><text x="${x(i)}" y="${h-14}" text-anchor="middle" font-size="10" fill="#67706f">${d.date.slice(5)}</text>`).join('')}</svg>`;$('#longitudinalMetrics').innerHTML=[metric('Baseline interference',first.value.toFixed(1),'',first.date),metric('Latest interference',last.value.toFixed(1),'',last.date),metric('Relative change',change.toFixed(1),'%','Negative = less interference'),metric('Comparable sessions',data.length,'','Same protocol family')].join('');$('#sessionTable').innerHTML=`<thead><tr><th>Date</th><th>Motor DTC</th><th>Cognitive DTC</th><th>Combined</th><th>Timing quality</th></tr></thead><tbody>${state.history.map(r=>`<tr><td>${r.date}</td><td>${r.motorDtc.toFixed(1)}%</td><td>${r.cognitiveDtc.toFixed(1)}%</td><td>${combinedInterference(r.motorDtc,r.cognitiveDtc).toFixed(1)}</td><td>${Math.round(r.reliability*100)}%</td></tr>`).join('')}</tbody>`}
function protocols(){$('#protocolGrid').innerHTML=cognitiveParadigms.map(p=>`<article class="protocol-card"><div class="icon">${p.code}</div><div class="eyebrow">${p.domain}</div><h3>${p.name}</h3><p>${p.description}</p><div class="protocol-tags">${p.parameters.map(t=>`<span>${t}</span>`).join('')}</div></article>`).join('')}
function kills(){const a=['Repeated measurements remain too unstable to distinguish change from noise.','Practice effects cannot be controlled by protocol design.','Sensor or platform latency prevents reliable event alignment.','Clinicians cannot interpret the two-domain report consistently.','Capacity maps depend so strongly on task choice that they do not generalise.','Device integration becomes bespoke engineering for every manufacturer.','Commercial buyers value entertainment but will not pay for measurement.','Observed gains remain confined to trained tasks without transfer.'];$('#killCriteria').innerHTML=a.map(t=>`<div class="check-row"><span>×</span><span>${t}</span></div>`).join('')}
function eventPreview(){const e=state.session?.events?.length?state.session.events.slice(-8):[{session_id:'demo-session',event_type:'protocol.transition',phase:'dual',status:'started',monotonic_timestamp_ms:0,protocol_version:'1.0.0'},{session_id:'demo-session',event_type:'cognitive.stimulus',phase:'dual',stimulus_type:'go-no-go',monotonic_timestamp_ms:1000.227,expected_response:'left'},{session_id:'demo-session',event_type:'cognitive.response',phase:'dual',monotonic_timestamp_ms:1619.821,response_latency_ms:619.6,correct:true},{session_id:'demo-session',event_type:'motor.sample',phase:'dual',motor_value:59.8,motor_unit:'rpm',monotonic_timestamp_ms:1750.102,device_id:'simulator-cycle-001'}];$('#eventPreview').textContent=JSON.stringify(e,null,2)}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function reset(){clearTimers();state.session=null;state.summary=null;state.phase=0;$('#assessmentState').textContent='Ready';$('#assessmentState').className='badge neutral';screen('assessmentSetup');rail(getProtocol($('#protocolSelect').value),-1);provenance();overview();eventPreview()}
function init(){$('#protocolSelect').innerHTML=assessmentProtocols.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');rail(getProtocol(assessmentProtocols[0].id));provenance();overview();protocols();kills();longitudinal();eventPreview();$$('.nav-item').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.view)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.jump)));$('#startAssessmentBtn').addEventListener('click',start);$('#skipPhaseBtn').addEventListener('click',completePhase);$('#runAgainBtn').addEventListener('click',reset);$('#resetDemoBtn').addEventListener('click',()=>{reset();toast('Demo state reset')});$('#protocolSelect').addEventListener('change',()=>{rail(getProtocol($('#protocolSelect').value));provenance()});$('#prioritySelect').addEventListener('change',provenance);$('#cadenceSlider').addEventListener('input',e=>state.simulator.setManual(e.target.value));$$('.response-key').forEach(b=>b.addEventListener('click',()=>respond(b.dataset.response)));addEventListener('keydown',e=>{if(e.key==='ArrowLeft')respond('left');if(e.key==='ArrowRight')respond('right')});$('#longitudinalMetric').addEventListener('change',longitudinal);$('#exportJsonBtn').addEventListener('click',()=>{exportJson(state.session);toast('JSON export generated')});$('#exportCsvBtn').addEventListener('click',()=>{if(!state.session?.events?.length)return toast('Run an assessment before CSV export');exportCsv(state.session);toast('CSV export generated')})}
init();
