import{mean,coefficientOfVariation,accuracy,median}from'./analytics.js';

export class CMISession{
  constructor({participantId,protocol,priority,motorTarget}){this.sessionId=crypto.randomUUID();this.participantId=participantId;this.protocolId=protocol.id;this.protocolVersion=protocol.version;this.priority=priority;this.motorTarget=Number(motorTarget);this.startedAt=new Date().toISOString();this.startedPerf=performance.now();this.events=[];this.phaseData={motor:{cadence:[]},cognitive:{responses:[]},dual:{cadence:[],responses:[]}}}
  stamp(eventType,payload={}){const event={session_id:this.sessionId,participant_pseudonym:this.participantId,protocol_id:this.protocolId,protocol_version:this.protocolVersion,event_id:crypto.randomUUID(),event_type:eventType,monotonic_timestamp_ms:Number((performance.now()-this.startedPerf).toFixed(3)),wall_clock_timestamp:new Date().toISOString(),clock_source:'performance.now()',estimated_clock_uncertainty_ms:4,...payload};this.events.push(event);return event}
  addMotorSample(phase,cadence){const bucket=this.phaseData[phase];if(bucket?.cadence)bucket.cadence.push(cadence);return this.stamp('motor.sample',{phase,motor_value:Number(cadence.toFixed(2)),motor_unit:'rpm',device_id:'simulator-cycle-001',device_adapter_version:'1.0.0'})}
  addStimulus(phase,stimulus){return this.stamp('cognitive.stimulus',{phase,stimulus_id:stimulus.id,stimulus_type:stimulus.type,expected_response:stimulus.expected})}
  addResponse(phase,stimulus,response,latencyMs){const correct=response===stimulus.expected;const record={correct,latencyMs,response,stimulusId:stimulus.id};const bucket=this.phaseData[phase];if(bucket?.responses)bucket.responses.push(record);return this.stamp('cognitive.response',{phase,stimulus_id:stimulus.id,cognitive_response:response,response_latency_ms:Number(latencyMs.toFixed(1)),correct})}
  addTransition(phase,status){return this.stamp('protocol.transition',{phase,status,priority_instruction:this.priority})}
  summary(){const motorBaseline=this.phaseData.motor.cadence;const cognitiveBaseline=this.phaseData.cognitive.responses;const dualCadence=this.phaseData.dual.cadence;const dualResponses=this.phaseData.dual.responses;return{sessionId:this.sessionId,participantId:this.participantId,protocolId:this.protocolId,protocolVersion:this.protocolVersion,priority:this.priority,motorBaseline:{meanCadence:mean(motorBaseline),cadenceCV:coefficientOfVariation(motorBaseline),n:motorBaseline.length},cognitiveBaseline:{accuracy:accuracy(cognitiveBaseline),medianRt:median(cognitiveBaseline.map(r=>r.latencyMs)),n:cognitiveBaseline.length},dualTask:{meanCadence:mean(dualCadence),cadenceCV:coefficientOfVariation(dualCadence),accuracy:accuracy(dualResponses),medianRt:median(dualResponses.map(r=>r.latencyMs)),motorN:dualCadence.length,cognitiveN:dualResponses.length},eventCount:this.events.length,timingQuality:'Research-ready',estimatedClockUncertaintyMs:4}}
}
